package feast.lphybeast.tobeast.values;

import beast.base.core.BEASTInterface;
import beast.base.core.Function;
import beast.base.inference.parameter.RealParameter;
import feast.function.Concatenate;
import lphy.base.distribution.WeightedDirichlet;
import lphy.core.model.Value;
import lphy.core.vectorization.VectorUtils;
import lphybeast.BEASTContext;
import lphybeast.ValueToBEAST;
import lphybeast.tobeast.operators.DefaultOperatorStrategy;
import lphybeast.tobeast.values.ValueToParameter;

import java.util.ArrayList;
import java.util.List;

/**
 * Handles Double[] values generated by WeightedDirichlet,
 * creating a Concatenate of individual RealParameters with delta exchange operator.
 * This overrides the core DoubleArrayValueToBEAST for WeightedDirichlet cases.
 */
public class DoubleArrayValueToBEAST implements ValueToBEAST<Double[], BEASTInterface> {

    @Override
    public BEASTInterface valueToBEAST(Value<Double[]> value, BEASTContext context) {

        if (value.getGenerator() instanceof WeightedDirichlet) {

            Concatenate concatenatedParameters = new Concatenate();
            Double[] values = value.value();

            List<Function> args = new ArrayList<>();
            for (int i = 0; i < values.length; i++) {
                RealParameter parameter = BEASTContext.createRealParameter(
                        value.getCanonicalId() + VectorUtils.INDEX_SEPARATOR + i, values[i]);
                context.addStateNode(parameter, value, false);
                args.add(parameter);
            }
            concatenatedParameters.setInputValue("arg", args);
            concatenatedParameters.initAndValidate();

            ValueToParameter.setID(concatenatedParameters, value);

            DefaultOperatorStrategy.addDeltaExchangeOperator(value, args, context);

            return concatenatedParameters;
        }

        // For non-WeightedDirichlet cases, return null to let core handler deal with it
        return null;
    }

    @Override
    public boolean match(Value value) {
        return value.value() instanceof Double[] && value.getGenerator() instanceof WeightedDirichlet;
    }

    @Override
    public Class getValueClass() {
        return Double[].class;
    }

    @Override
    public Class<BEASTInterface> getBEASTClass() {
        return BEASTInterface.class;
    }
}
