name: LPhy BEAST Ext tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-lphybeast:
    runs-on: ubuntu-latest

    steps:
      # must under LPhyBeast folder, otherwise build will fail
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: LPhyBeastExt

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'

      ###TODO: require version.xml, so check out all depended B2 pkg
      - name: Set environmental variables
        run: |
          pwd
          ls LPhyBeastExt
          echo "BEAST_LIB=LPhyBeastExt/lphybeast-ext/lib" >> $GITHUB_ENV
          echo "LAUNCHER=launcher-2.7.3.jar" >> $GITHUB_ENV
          echo "REPO_DIR=/home/runner/.beast/2.7" >> $GITHUB_ENV

      # /home/runner/.beast/2.7
      - name: Install packages
        run: |
          java -Djava.library.path="$BEAST_LIB" -cp "$BEAST_LIB/$LAUNCHER" beast.pkgmgmt.PackageManager -add bdtree
          java -Djava.library.path="$BEAST_LIB" -cp "$BEAST_LIB/$LAUNCHER" beast.pkgmgmt.PackageManager -add BEAST_CLASSIC
          java -Djava.library.path="$BEAST_LIB" -cp "$BEAST_LIB/$LAUNCHER" beast.pkgmgmt.PackageManager -add BEASTLabs
          java -Djava.library.path="$BEAST_LIB" -cp "$BEAST_LIB/$LAUNCHER" beast.pkgmgmt.PackageManager -add FastRelaxedClockLogNormal
          java -Djava.library.path="$BEAST_LIB" -cp "$BEAST_LIB/$LAUNCHER" beast.pkgmgmt.PackageManager -add feast
          java -Djava.library.path="$BEAST_LIB" -cp "$BEAST_LIB/$LAUNCHER" beast.pkgmgmt.PackageManager -add SSM
          java -Djava.library.path="$BEAST_LIB" -cp "$BEAST_LIB/$LAUNCHER" beast.pkgmgmt.PackageManager -add Mascot
          java -Djava.library.path="$BEAST_LIB" -cp "$BEAST_LIB/$LAUNCHER" beast.pkgmgmt.PackageManager -add MM
          java -Djava.library.path="$BEAST_LIB" -cp "$BEAST_LIB/$LAUNCHER" beast.pkgmgmt.PackageManager -add SA
      # https://github.com/CompEvol/beast2/issues/1078
      - name: Install beast2 base
        run: |
          ls $REPO_DIR
          mkdir $REPO_DIR/BEAST.base
          cp $BEAST_LIB/BEAST.base.version.xml $REPO_DIR/BEAST.base/version.xml
          mkdir $REPO_DIR/BEAST.base/lib
          cp $BEAST_LIB/BEAST-base-*.jar $REPO_DIR/BEAST.base/lib

      - name: Check file paths
        run: |
          find . -name "lib"
          ls LPhyBeastExt/lphybeast-ext
      - name: Check all packages
        run: ls $REPO_DIR/*/lib

      - name: Install lphybeast
        # change working dir, so gradle will work
        working-directory: ./LPhyBeastExt
        # gradle will download lphybeast from Maven repo database
        run: |
          ./gradlew build -x test --no-daemon
          ./gradlew build -x test --no-daemon
          pwd
          ls lphybeast-ext/build
          ls lphybeast-ext/build/lphybeast

      - name: Run unit tests
        # change working dir, so gradle will work
        working-directory: ./LPhyBeastExt
        # run test
        run: ./gradlew test --no-daemon

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ./LPhyBeastExt/*/build/test-results/**/*.xml