name: LPhy BEAST Ext tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-lphybeast:
    runs-on: ubuntu-latest

    steps:
      # must under LPhyBeast folder, otherwise build will fail
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: LPhyBeastExt

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'

      - name: Check file paths
        run: |
          pwd
          ls LPhyBeastExt
          find . -name "lib"
          ls LPhyBeastExt/lphybeast-ext

      - name: Run unit tests
        # change working dir, so gradle will work
        working-directory: ./LPhyBeastExt
        # TODO tests not working
        run: ./gradlew build -x test --no-daemon

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ./LPhyBeastExt/*/build/test-results/**/*.xml