name: Lphy BEAST tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-lphybeast:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Checkout LPhyBEAST
        uses: actions/checkout@v2
        with:
          repository: LinguaPhylo/LPhyBEAST
          path: LPhyBEAST

      - name: Checkout Lphy
        uses: actions/checkout@v2
        with:
          repository: LinguaPhylo/linguaPhylo
          path: linguaPhylo

      - name: Checkout outercore
        uses: actions/checkout@v2
        with:
          repository: LinguaPhylo/beast-outercore
          path: beast-outercore

      - name: Find build.xml
        run: |
          pwd
          find . -name "build.xml"

      - name: Run LPhy BEAST Ant
        # must run build from the folder where it is
        run: |
          pwd
          cd ./LPhyBEAST
          ant -noinput -buildfile ./build.xml github-actions

