name: Lphy BEAST tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-lphybeast:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      # must under LPhyBEAST folder, otherwise build will failed
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: LPhyBeast

      - name: Checkout Lphy
        uses: actions/checkout@v2
        with:
          repository: LinguaPhylo/linguaPhylo
          path: linguaPhylo

      - name: Checkout outercore
        uses: actions/checkout@v2
        with:
          repository: LinguaPhylo/beast-outercore
          path: beast-outercore

      - name: Find build.xml
        run: |
          pwd
          find . -name "build.xml"
          find . -name "lib"
          ls LPhyBeast/lib

      - name: Run LPhy BEAST Ant
        working-directory: ./LPhyBeast
        # must run build from the folder where it is
        run: ant -noinput -buildfile ./build.xml github-actions

 # |
 # pwd
 # cd ./LPhyBEAST
