name: Lphy BEAST tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-lphybeast:
    runs-on: ubuntu-latest
    env:
      working-directory: ./

    steps:
      - name: Checkout LphyBEAST
        uses: actions/checkout@v2
        with:
          path: main

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15.0.1

      - name: Checkout Lphy
        uses: actions/checkout@v2
        with:
          repository: LinguaPhylo/linguaPhylo
          path: linguaPhylo

      - name: Checkout outercore
        uses: actions/checkout@v2
        with:
          repository: LinguaPhylo/beast-outercore
          path: beast-outercore

      - name: tests
        run: |
          echo ${{env.working-directory}}
          echo ${{github.workspace}}
          echo ${{GITHUB_WORKSPACE}}

      - name: Run Lphy BEAST Ant
        run: ant -noinput -buildfile build.xml github-actions
        working-directory: ${{env.working-directory}}
