name: Lphy BEAST tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-lphybeast:
    runs-on: ubuntu-latest

    steps:
      # must under LPhyBeast folder, otherwise build will fail
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: LPhyBeast
#      - name: Checkout Lphy
#        uses: actions/checkout@v3
#        with:
#          repository: LinguaPhylo/linguaPhylo
#          path: linguaPhylo

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'

      ###TODO: require version.xml, so check out all depended B2 pkg


      #./linguaPhylo/lphy/lib
      #./LPhyBeast/lphybeast/lib
      - name: Check file paths
        run: |
          pwd
          ls LPhyBeast
          find . -name "lib"
          ls LPhyBeast/lphybeast/lib

      - name: Run unit tests
        # change working dir, so gradle will work
        working-directory: ./LPhyBeast
        # only available in lphy at the moment
        # temp disable test because of github issue
        run: ./gradlew build -x test --no-daemon

#      - name: Publish unit test results
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        if: always()
#        with:
#          files: ./LPhyBeast/*/build/test-results/**/*.xml