name: Lphy BEAST tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-lphybeast:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
          cache: 'gradle'
      # must under LPhyBeast folder, otherwise build will failed
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: LPhyBeast
      - name: Checkout Lphy
        uses: actions/checkout@v2
        with:
          repository: LinguaPhylo/linguaPhylo
          path: linguaPhylo

      - name: ls libs
        run: |
          pwd
          find . -name "lib"
          ls LPhyBeast/lphybeast/lib

      - name: Run unit tests
        # only available in lphy at the moment
        run: ./gradlew :lphybeast:test --no-daemon

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: lphybeast/build/test-results/**/*.xml
